### PR TITLE
docs: update FAQ.adoc

### PR DESCRIPTION
**Pull request by marcobonita**
Added a description about Kubernetes and how it's used

In addition:
  - fix contributions check errors
    - add "description" AsciiDoc attribute
    - remove hard coded link to the documentation site and use xref instead
  - fix typos

### CODE REVIEW

**Review by uguy — DISMISSED** [review]

**Comment by marcobonita** [comment]
@uguy as far as I can tell, there are only 2 branches on bonita-cloud-doc: master and dependabot/github_actions/peter-evans/repository-dispatch-3
What would you recommend?

**Comment by uguy** [comment]
> @uguy as far as I can tell, there are only 2 branches on bonita-cloud-doc: master and dependabot/github_actions/peter-evans/repository-dispatch-3 What would you recommend?

The `main` branch is fine then. I approved too quickly be cause I read the PR too quickly. I though it was on engine doc with those many versions...

LGTM

**Review by uguy — APPROVED** [review]

**Review by tbouffard — CHANGES_REQUESTED** [review]
:x: Contribution checks failed at least because the description attribute is missing in the page. 
The error previously existed (not due to this PR) but it is only detected now.
I will manage it

image

**Comment by tbouffard** [comment]
ℹ️ ab24325 fix the missing "description" AsciiDoc attribute
❌ The page still includes forbidden patterns

image

**Review by tbouffard — APPROVED** [review]
✔️ 80b8227 fix the latest "contribution checks" errors

Notice that there are other pages in the bonita-cloud documentation that contain such errors. This is out of the scope of this PR to fix them, but it can be used as a guideline for future fixes.

@marcobonita I let you review the text I put in the description. Feel free to update it.
When it will be OK for you, I will merge the PR.

**Comment by marcobonita** [comment]
hello @tbouffard, looks good to me! thanks a lot

**Pull request merged**
