### PR TITLE
feat(custom-deployjson): update documentation

### PR DESCRIPTION
**Pull request by alexisries**

### CODE REVIEW

**Comment by alexisries** [comment]
Please do not merge until this PR is merged and deployed to all customers environments: https://github.com/bonitasoft-cloud/bcld-jenkins/pull/30

**Comment by JeremJR** [comment]
Thx @alexisries 
As discussed I have updated screenshots and added more info about deployment policies in https://github.com/bonitasoft/bonita-cloud-doc/pull/25/commits/f0843632c859da92806b4288300f886baa02abba
I have also renamed the PR to match the new requirements of https://github.com/bonitasoft/bonita-cloud-doc/pull/28
On my side, it seems OK and could be merged once the feature will be deployed.

**Review by JeremJR — APPROVED** [review]

**Comment by DumitruCorini** [comment]
@alexisries @JeremJR Hello, this pr seems to be breaking our pr on the documentation website. We can't seem to build the preview of the pr because some files are missing from the Continuous_Delivery_Deploying_a_Living_Application_to_Bonita_Cloud.adoc file.
PR: https://github.com/bonitasoft/bonita-doc/pull/2063
Build: https://github.com/bonitasoft/bonita-doc/runs/6771779240?check_suite_focus=true

**Comment by JeremJR** [comment]
As discussed, we will let you check this issue with @benjaminParisel and/or @tbouffard

**Pull request merged**
