### PR TITLE
feat(test-toolkit): add integration test documentation

### PR DESCRIPTION
**Pull request by alexisries**

### CODE REVIEW

**Review by rbioteau — CHANGES_REQUESTED** [review]
Use the antora component xfref to be redirected to the latest version

**Comment by JeremJR** [comment]
I have made a PR to resolve the current conflicts into this branch by taking last changes from master and adding some improvements about Test Toolkit
https://github.com/bonitasoft/bonita-cloud-doc/pull/30

**Review by JeremJR — APPROVED** [review]
OK for me, but it should be merged only when this feature will be deployed.

**Review by rbioteau — APPROVED** [review]

**Comment by tbouffard** [comment]
ℹ️ for information, I added a check to ensure that links using documentation.bonitasoft.com are not introduced within the documentation, see #28
We are working on providing more automatic checks to improve the quality of the documentation content by providing shared tooling stored in https://github.com/bonitasoft/bonita-documentation-site/

**Pull request merged**
